baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
googleAnalytics = "UA-178435018-1"

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 5
  showReadingTime = false

[languages]
  [languages.en]
    title = "trevor mckay"
    subtitle = ""
    keywords = "blog, posts, portfolio, development, coding"
    copyright = "© 2020 Trevor McKay"
    menuMore = "Show more"
    writtenBy = "Written by Trevor McKay"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "/home/trevor_mckay "
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "LinkedIn"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/trevor-mckay-1602a5180/"
      [[languages.en.menu.main]]
        identifier = "GitHub"
        name = "GitHub"
        url = "https://github.com/trmckay"
