version: "3"

services:
  build:
    image: klakegg/hugo:latest
    restart: "no"
    volumes:
      - ./:/src

  caddy:
    build: .
    restart: unless-stopped
    depends_on:
      - build
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/srv:ro

volumes:
  caddy_data:
  caddy_config:
